Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./conf", "/vagrant/conf"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end

  config.vm.define "vkazanavS" do |config|
    config.vm.network "private_network", ip: "192.168.56.110"

    config.vm.hostname = "vkazanavS"

    config.vm.provider "virtualbox" do |vb|
      vb.name = "vkazanavS"
      vb.cpus = 2
      vb.memory = "2048"
    end

    config.vm.provision :shell, inline: <<-SHELL
      export DEBIAN_FRONTEND=noninteractive
      apt update
      apt upgrade -y
    SHELL

    config.vm.provision :shell, inline: <<-SHELL
      curl -sfL https://get.k3s.io | \
      sh -s - server \
        --write-kubeconfig-mode=644 \
        --token=12345 \
        --node-ip=192.168.56.110 \
        --advertise-address=192.168.56.110

      echo "k3s server is up"
    SHELL

    config.vm.provision :shell, inline: <<-SHELL
      echo "deploying deployments"
      cd /vagrant/conf
      kubectl apply -f redmine.yaml
      kubectl apply -f nginx.yaml
      kubectl apply -f whoami.yaml
      kubectl apply -f ingres.yaml

      echo "192.168.56.110 app1 app2 app3" >> /etc/hosts
    SHELL

    config.vm.provision :shell, inline: <<-SHELL
      apt install -y kubuntu-desktop firefox --no-install-recommends

      PASS='$6$Hp1SeIUZi7Lckwq/$YWaopZpx6/x6UYJ1UmljK8Ang60BBrc7i6df8qbBBSXYyWqLmnud919Y6OGpARgY.6kIANNTQ3JPBArjWwSe31'
      useradd -m -p "$PASS" -s /bin/bash vaiva

      mkdir -p /etc/sddm.conf.d/
      cat > /etc/sddm.conf.d/auto-login.conf <<EOF
[Users]
HideUsers=vagrant

[Autologin]
User=vaiva
Relogin=true
Session=plasma.desktop
EOF

      service sddm start
    SHELL
  end
end
