Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  # config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
  end

  config.vm.provision :shell, inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive
    apt update
    apt purge --autoremove -y snap snapd
    apt upgrade -y
  SHELL

  config.vm.define "vkazanavS" do |config|
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

    config.vm.hostname = "vkazanavS"

    config.vm.provider "virtualbox" do |vb|
      vb.name = "vkazanavS"
      vb.cpus = 2
      vb.memory = "2048"
    end

    config.vm.provision :shell, inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s - server --write-kubeconfig-mode=644 --token=12345
      echo "k3s server is up"
    SHELL
  end

  config.vm.define "vkazanavSW" do |config|
    config.vm.network "private_network", ip: "192.168.56.111"
    config.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: true

    config.vm.hostname = "vkazanavSW"

    config.vm.provider "virtualbox" do |vb|
      vb.name = "vkazanavSW"
      vb.cpus = 1
      vb.memory = "1024"
    end

    config.vm.provision :shell, inline: <<-SHELL
      curl -sfL https://get.k3s.io | sh -s - agent --server=https://192.168.56.110:6443 --token=12345
      echo "k3s agent is up"
    SHELL
  end
end
