Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_check_update = false
  config.vm.hostname = "p3-vm"

  config.vm.network "private_network", ip: "192.168.56.120"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.synced_folder "/home/bfiguet/sgoinfre/iot/p3",
                        "/home/vagrant/p3",
                        type: "virtualbox"

end
