apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - name: redmine
        image: "redmine:6.1.0-alpine3.23"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: redmine
spec:
  selector:
    app: redmine
  ports:
  - port: 3000
    targetPort: 3000
